### PR TITLE
Cherry-picked memory fixes from fix/stack-initialization

### PR DESCRIPTION
**Pull request by mikeger**
Copy of memory-related fixes from https://github.com/wireapp/wire-ios-data-model/pull/320

### CODE REVIEW

**Comment by daehn** [comment]
@mikeger looks like an API breaker with the changes to the name generator?

**Comment by mikeger** [comment]
Good point, I will check now.

**Comment by mikeger** [comment]
I cannot find the usage of `nameGenerator` in other frameworks, most likely they are going directly to the users for the names.

**Comment by daehn** [comment]
Either way I would make this a major release as some methods have been removed, irregardless whether someone was actually using them or not.

**Pull request merged**
