### PR TITLE
revert: Self-deleting messages SQSERVICES-1018

### PR DESCRIPTION
**Pull request by KaterinaWire**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1018" title="SQSERVICES-1018" target="_blank">TaskSQSERVICES-1018</a>  Revert self-deleting messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Revert self-deleting messages

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by typfel** [comment]
You haven't reverted all the debugging commits like:
 https://github.com/wireapp/wire-ios-data-model/commit/c86c17d65495191c22575d415cf908d0dc18c114
 https://github.com/wireapp/wire-ios-data-model/commit/ddd6ea2529ce8e6280484c7f549905a78a398e3d
 https://github.com/wireapp/wire-ios-data-model/commit/624a811dc7c34bc365c87fb4e8946ef762e718d1

**Review by typfel — CHANGES_REQUESTED** [review]
All debug changes haven't been reverted

**Comment by KaterinaWire** [comment]
> You haven't reverted all the debugging commits like:
> [c86c17d](https://github.com/wireapp/wire-ios-data-model/commit/c86c17d65495191c22575d415cf908d0dc18c114)
> [ddd6ea2](https://github.com/wireapp/wire-ios-data-model/commit/ddd6ea2529ce8e6280484c7f549905a78a398e3d)
> [624a811](https://github.com/wireapp/wire-ios-data-model/commit/624a811dc7c34bc365c87fb4e8946ef762e718d1)

Hmm, I did` git revert 9c4b79e439b53f06c1fab6a253ecd2058b357dc3 624a811dc7c34bc365c87fb4e8946ef762e718d1 c86c17d65495191c22575d415cf908d0dc18c114 ddd6ea2529ce8e6280484c7f549905a78a398e3d`

**Review by typfel — APPROVED** [review]

**Review by johnxnguyen — APPROVED** [review]

**Comment by KaterinaWire** [comment]
release major

**Pull request merged**
