### PR TITLE
Only maintain one set of participants

### PR DESCRIPTION
**Pull request by typfel**
## What's new in this PR?

Refactor the code for participants to only maintain a single set of participants which is always the last known server state.

## Todo

- [x] database migration test

### CODE REVIEW

**Comment by daehn** [comment]
@typfel conflicts!

**Comment by mikeger** [comment]
@typfel I would have to write the migration test anyway for the ephemeral fix. Should we merge this one in so I can proceed with it?

**Comment by mikeger** [comment]
@typfel please review

**Comment by typfel** [comment]
@mikeger reviewed. (can't approve my own PR)

**Pull request merged**
