### PR TITLE
Add function to copy a folder recursively

### PR DESCRIPTION
**Pull request by marcoconti83**

### CODE REVIEW

**Comment by typfel** [comment]
I thought the old code was already supposed to copy recursively. Could you explain what changed?

**Comment by marcoconti83** [comment]
The old code moves. The new code copies. 
I refactored in one single function as the only difference was whether we were calling "copy" or "move" on the individual items.

**Comment by vytis** [comment]
Does this have any CoreData related code? Maybe WireUtilities is a better place for it?

**Comment by marcoconti83** [comment]
@vytis good point. I think there are more file-system related extensions that would be good to move. I would put in this PR and then go through all those and move them in another PR.

**Pull request merged**
