### PR TITLE
[Refactor] Extend PushToken class

### PR DESCRIPTION
**Pull request by KaterinaWire**
## What's new in this PR?

Move `PushTokenType` from the SE.

### CODE REVIEW

**Review by marcomaddy1982 — APPROVED** [review]

**Review by johnxnguyen — CHANGES_REQUESTED** [review]
Do you mean to nest `TokenType` inside `PushToken`? It makes little sense to nest it inside a different struct.

**Comment by KaterinaWire** [comment]
> Do you mean to nest `TokenType` inside `PushToken`? It makes little sense to nest it inside a different struct.

Yep, it make sense to do it inside `PushToken`. But in SE I need to have access to the PushTokenType.transportType, so I would like to keep it outside of `PushToken` struct.

**Review by johnxnguyen — APPROVED** [review]
> Yep, it makes sense to do it inside PushToken. But in SE I need to have an access to the PushTokenType.transportType, so I would like to keep it outside of PushToken struct.

You can still access it if you mark it as `public`.

**Comment by KaterinaWire** [comment]
> > Yep, it makes sense to do it inside PushToken. But in SE I need to have an access to the PushTokenType.transportType, so I would like to keep it outside of PushToken struct.
> 
> You can still access it if you mark it as `public`.

Moved to the `PushToken`

**Pull request merged**
