### PR TITLE
Do not crash when sending the ephemeral to an empty group

### PR DESCRIPTION
**Pull request by mikeger**
- Optional here and there to allow indication of the fact that the payload cannot be generated.

### CODE REVIEW

**Comment by daehn** [comment]
@mikeger what happens when we are unable to generate an encrypted message payload? Will we endlessly retry?

**Comment by mikeger** [comment]
@daehn message would expire without sending: https://github.com/wireapp/wire-ios-message-strategy/pull/86/files

**Comment by basine** [comment]
Hmm, I thought we had fixed that before?

**Comment by mikeger** [comment]
Closed in favor of https://github.com/wireapp/wire-ios-data-model/pull/316

**Pull request closed without merging**
