### PR TITLE
ExpiredDate! = nil at the time of the query is not using the index to…

### PR DESCRIPTION
**Pull request by wjwjwj2223**
https://github.com/wireapp/wire-ios/issues/4431

### CODE REVIEW

**Comment by zenkins** [comment]
Can one of the admins verify this patch?

**Comment by wjwjwj2223** [comment]
Of course you can verify

**Comment by wjwjwj2223** [comment]
you can see  https://github.com/wireapp/wire-ios/issues/4431

**Comment by johnxnguyen** [comment]
Hi @wjwjwj2223 👋, thanks for the contribution! We're always happy to see people diving in to the project. We'll take a look at this as soon as we are able to.

**Comment by typfel** [comment]
This will be merged in https://github.com/wireapp/wire-ios-data-model/pull/1054. We can't merge this PR as it is since the fetch request doesn't compile.

**Pull request closed without merging**
