### PR TITLE
ZIOS-10707: Subtitle is not updated properly if the message is edited

### PR DESCRIPTION
**Pull request by nicorsm**
### Issues

Subtitles inside the cells of the conversation list was not updated after editing a message and posting a mention.

### Solutions

I've added `messagesChanged` to the whitelist of allowed change types inside of `conversationDidChange()`.

### CODE REVIEW

**Comment by mikeger** [comment]
Would be good to have the test for this change!

**Comment by mikeger** [comment]
@typfel can you check this one? I think we are not sending the update intentionally, since the cell is observing the message changes?

**Comment by typfel** [comment]
@mikeger from what I can see is the cell no observing the messages directly.

**Comment by nicorsm** [comment]
@zenkins release minor

**Pull request merged**
