### PR TITLE
Add unavailable transfer state and check it before starting download

### PR DESCRIPTION
**Pull request by daehn**
## What's new in this PR?

* Add unavailable transfer state and check it before starting download.

### CODE REVIEW

**Comment by vytis** [comment]
Small test for this maybe?

**Comment by daehn** [comment]
@vytis there are some tests added in the request strategy PR, but I'll make sure to add one to check the added branch here as well.

**Comment by daehn** [comment]
@vytis updated!

**Comment by daehn** [comment]
@zenkins release minor

**Comment by daehn** [comment]
Actually thinking about it adding an enum value is an API breaker (exhaustive switches), should probably have been a major instead.

**Pull request merged**
