### PR TITLE
fixed searching issue

### PR DESCRIPTION
**Pull request by billypchan**
### Issues

Searching has no return after search with a query ended with space

### Causes

The searching does not finish when a empty query

### Solutions

Trim the query string before break down it into array.

### CODE REVIEW

**Comment by marcoconti83** [comment]
I don't understand how the code was broken. Can you explain why it was freezing?

**Comment by billypchan** [comment]
@marcoconti83 When executing a query with precidate `NSPredicate(format: "ANY %K.user != %@ AND ANY %K.user.normalizedName MATCHES %@", ZMConversationParticipantRolesKey, selfUser, ZMConversationParticipantRolesKey, strSearchQuery)`, if the later parameter is empty string, the query is never done.

**Comment by marcoconti83** [comment]
Thanks for the explanation @billypchan !

**Comment by billypchan** [comment]
@zenkins release patch

**Pull request merged**
