### PR TITLE
ZIOS-10124 - Store the synced timer per conversation

### PR DESCRIPTION
**Pull request by nicorsm**
I've added the `messageTimer` field inside the Core Data model. Original field from backend side is `message_timer`.

(Let me know if I missed something)

### CODE REVIEW

**Comment by mikeger** [comment]
Hey, I've implemented it yesterday already, was not aware somehow that you are also working on it

**Comment by mikeger** [comment]
https://github.com/wireapp/wire-ios-data-model/pull/493

**Comment by mikeger** [comment]
:hurtrealbad:

**Comment by nicorsm** [comment]
No problem, I've implemented it on Friday but I was waiting for parameter name from backend. I'll close it ❌

**Pull request closed without merging**
