### PR TITLE
Better way of detecting bots (Anna and Otto)

### PR DESCRIPTION
**Pull request by mikeger**
- It came out that the user id for Otto would still have to change, so it was decided to go on with email detection

### CODE REVIEW

**Comment by marcoconti83** [comment]
Looks good! Please release

**Comment by marcoconti83** [comment]
... once Travis is passed :)

**Comment by mikeger** [comment]
@marcoconti83 passed!

**Comment by mikeger** [comment]
... and failed, but failed looks like the fail in the middle of testing

**Pull request merged**
